<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\User::create([
            'name' => 'Aktiv Digiatal',
            'username' => 'aktivdigital',
            'password' => Hash::make('Adm123#'),
            'role' => 'admin',
            'email' => 'test@example.com',
        ]);

        \App\Models\ShippingMethod::create([
            'name' => 'MPL'
        ]);

        \App\Models\ShippingMethod::create([
            'name' => 'GLS'
        ]);

        \App\Models\ShippingMethod::create([
            'name' => 'DPD'
        ]);

        DB::unprepared('INSERT INTO `country` (`name`, `created_at`, `updated_at`) VALUES
("Afganisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Albánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Algéria", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Andorra", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Angola", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Antigua és Barbuda", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Argentína", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ausztrália", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ausztria", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Azerbajdzsán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bahama-szigetek", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bahrein", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Banglades", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Barbados", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Belgium", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Belize", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Benin", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bhután", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bolívia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bosznia-Hercegovina", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Botswana", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Brazília", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Brunei", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Bulgária", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Burkina Faso", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Chile", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ciprus", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kolumbia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kongói Demokratikus Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kongói Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Dánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Dél-afrikai Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Dominikai Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Dominikai Közösség", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Dzsibuti", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ecuador", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Egyesült Arab Emirátusok", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Egyesült Királyság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Egyiptom", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Elefántcsontpart", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Észtország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Etiópia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Fehéroroszország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Finnország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Franciaország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Gabon", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Gambia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ghána", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Görögország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Grúzia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Guatemala", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Guinea", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Guinea-Bissau", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Guyana", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Hollandia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Honduras", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Horvátország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("India", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Indonézia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Irak", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Irán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Írország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Izland", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Izrael", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Jamaica", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Japán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Jemen", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Jordánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kambodzsa", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kamerun", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kanada", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Katar", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kazahsztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kenya", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kína", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kirgizisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kiribati", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kolumbia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kongói Demokratikus Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kongói Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Koreai Köztársaság", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Koszovó", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kuba", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Kuvait", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Laosz", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Lettország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Libanon", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Libéria", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Líbia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Liechtenstein", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Litvánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Luxemburg", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Madagaszkár", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Magyarország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Malajzia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Malawi", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Maldív-szigetek", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mali", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Málta", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Marokkó", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mauritius", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mexikó", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mianmar", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Moldova", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Monaco", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mongólia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Montenegró", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Mozambik", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Namíbia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Nauru", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Németország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Nepál", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Niger", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Nigéria", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Nicaragua", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Norvégia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Nyugat-Szahara", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Óceánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Omán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Oroszország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Örményország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Palesztina", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Panama", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Pakisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Pápua Új-Guinea", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Paraguay", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Peru", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Portugália", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ruanda", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Románia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Salamon-szigetek", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Salvador", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("San Marino", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Sao Tome és Principe", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szenegál", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szerbia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Seychelles", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Sierra Leone", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szíria", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szomália", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Spanyolország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Srí Lanka", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szent Kitts és Nevis", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szent Lúcia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szent Vincent és Grenadine-szigetek", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szingapúr", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szlovákia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szlovénia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szudán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Suriname", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Svájc", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Svédország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Szváziföld", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Tádzsikisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Tanzánia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Thaiföld", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Togo", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Tonga", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Trinidad és Tobago", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Tunézia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Törökország", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Türkmenisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Uganda", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Ukrajna", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Uruguay", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Üzbegisztán", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Venezuela", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Vietnám", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Zambia", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '"),
("Zimbabwe", "' . date('Y-m-d H:i:s') . '", "' . date('Y-m-d H:i:s') . '")');
    }
}
